version: 2

updates:
  - package-ecosystem: nuget
    directory: "/"
    target-branch: "dev" 
    schedule:
      interval: weekly
    labels:
      - "nuget"
      - "dependencies"

  - package-ecosystem: npm
    directory: /src/Bing.Wallpaper/ClientApp
    target-branch: "dev"
    schedule:
      interval: weekly
    labels:
      - "npm"
      - "dependencies"   