version: "3.7"

services:
  bing_wallpaper:
    build:
      context: .
      dockerfile: ./Dockerfile # 빌드 파일
    image: bbonkr/bing_wallpaper:latest # 도커 이미지 명칭
    container_name: bing_wallpaper # 컨테이너 명칭
    restart: always
    ports:
      - 5000:5000
    environment:
      - TZ=Asia/Seoul
      - ASPNETCORE_ENVIRONMENT=Production
      - App__DestinationPath=/app/images
      - ConnectionStrings__Default=<database connection string here>
      - Collector__Schedule=0 0 1 * * *
    volumes:
      - "${DESTINATION_PATH}:/app/images"
      - "${THUMBNAIL_PATH}:/app/thumbnails"
    network_mode: bridge
    # networks:
    #   - app-network
# networks:
#   app-network:
#     external:
#       name: app-network
