version: "3.7"

services:
  bing_wallpaper_service:
    build: 
      context: .
      dockerfile: ./Dockerfile # 빌드 파일
    image: bbonkr/bing_wallpaper:latest # 도커 이미지 명칭
    container_name: bing_wallpaper # 컨테이너 명칭
    restart: always
    environment:
      - TZ=Asia/Seoul
    volumes:
      - "${DESTINATION_PATH}:/app/images"
      - "${PWD}/.config/appsettings.json:/app/appsettings.json"
