version: "3.7"

services:
  bing_wallpaper_service:
    build: 
      context: .
      dockerfile: ./service.Dockerfile # 빌드 파일
    image: bbonkr/bing_wallpaper_service:latest # 도커 이미지 명칭
    container_name: bing_wallpaper_service # 컨테이너 명칭
    restart: always
    environment:
      - TZ=Asia/Seoul
      # - "DOTNETCORE_App__DestinationPath=/app/images"
      # - "DOTNETCORE_App__RunAtTime=${RUN_AT_TIME}"
      # - "DOTNETCORE_ConnectionStrings__Default=${CONNECTION_STRING}"
    volumes:
      - "${DESTINATION_PATH}:/app/images"
      - "${PWD}/.config/appsettings.json:/app/appsettings.json"
