// <auto-generated />
using System;
using Bing.Wallpaper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bing.Wallpaper.Data.SqlServer.Migrations
{
    [DbContext(typeof(DefaultDatabaseContext))]
    [Migration("20210924080913_Add image width,height")]
    partial class Addimagewidthheight
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bing.Wallpaper.Entities.AppLog", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasDefaultValueSql("newid()")
                        .HasComment("식별자");

                    b.Property<string>("Callsite")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("사이트");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("예외");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("로그 레벨");

                    b.Property<DateTimeOffset>("Logged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("sysdatetimeoffset()")
                        .HasComment("작성시각");

                    b.Property<string>("Logger")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("로거");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("장치");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("메시지");

                    b.HasKey("Id");

                    b.ToTable("AppLogs");

                    b
                        .HasComment("로깅 NLog");
                });

            modelBuilder.Entity("Bing.Wallpaper.Entities.ImageInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("newid()")
                        .HasComment("식별자");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("기준 URL");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("sysdatetimeoffset()")
                        .HasComment("작성시각");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Bing.Wallpaper.Entities.ImageInfo", b =>
                {
                    b.OwnsOne("Bing.Wallpaper.Entities.ImageMetadata", "Metadata", b1 =>
                        {
                            b1.Property<string>("ImageInfoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Copyright")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasComment("저작권");

                            b1.Property<string>("CopyrightLink")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasComment("저작권 링크");

                            b1.Property<int?>("Height")
                                .HasColumnType("int");

                            b1.Property<string>("Origin")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasComment("원본 위치");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasComment("제목");

                            b1.Property<int?>("Width")
                                .HasColumnType("int");

                            b1.HasKey("ImageInfoId");

                            b1.ToTable("Images");

                            b1.WithOwner()
                                .HasForeignKey("ImageInfoId");
                        });

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
