name: "PR completed"

on: # rebuild any PRs and main branch changes
  pull_request:
    types: ["closed"]

permissions:
  contents: write
  pull-requests: write
  issues: write

env:
  MAIN_BRANCH_NAME: main
  DEFAULT_BRANCH_NAME: dev
  PROJECT_NAME: "" # Repository project only; ORG project not supported
  DOTNET_VERSION: 8.0.x
  NODE_VERSION: 18

jobs:
  build: # make sure build/ci work properly
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: build ClientApp
        run: |
          cd src/Bing.Wallpaper/ClientApp
          npm ci
          npm run build

      - name: Restore dependencies
        run: dotnet restore

      - name: Build ASP.NET Core app
        run: dotnet build --no-restore

      - name: Logging
        run: |
          echo "👍 There is no error. "

  create-tag:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.next_version_proposal.outputs.next_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "get next version name"
        uses: bbonkr/next-version-proposal-action@v1
        id: next_version_proposal
        with:
          github_token: ${{ github.token }}
          pr: ${{ github.event.pull_request.number }}
          major_labels: "major,next"
          minor_labels: "enhancement,feature"
          patch_labels: "bug,documentation,chore,dependencies"
          next_version_prefix: "v"

      - name: "Create tag"
        uses: rickstaa/action-create-tag@v1
        if: ${{ steps.next_version_proposal.outputs.next_version != '' }}
        with:
          tag: "${{ steps.next_version_proposal.outputs.next_version }}"
          message: "New release ${{ steps.next_version_proposal.outputs.next_version }}"
          commit_sha: ${{ github.sha }}

      - name: git tag skipped
        if: ${{ steps.next_version_proposal.outputs.next_version == '' }}
        run: |
          echo "Next version tag is empty."
          exit 1

  create-release:
    needs: [build, create-tag]
    runs-on: ubuntu-latest
    if: ${{ needs.create-tag.outputs.next_version != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Logging
        run: |
          echo "next_version=${{ needs.create-tag.outputs.next_version }}"

      - name: create GitHub Release
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        if: ${{ needs.create-tag.outputs.next_version != '' }}
        with:
          config-name: release-drafter.yml
          version: ${{ needs.create-tag.outputs.next_version }}
          publish: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}

  create-pull:
    needs: [build, create-tag, create-release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get overview of PULL_REQUEST
        uses: bbonkr/get-overview-of-pull-requests-action@v1
        id: get_overview
        with:
          github_token: ${{ github.token }}
          base: ${{ env.MAIN_BRANCH_NAME }}
          head: ${{ github.event.pull_request.base.ref }}
          default_branch: ${{ env.DEFAULT_BRANCH_NAME }}

      - name: logging
        run: |
          echo "title:       ${{ steps.get_overview.outputs.title }}"
          echo "body:        ${{ steps.get_overview.outputs.body }}"
          echo "labels:      ${{ steps.get_overview.outputs.labels }}"
          echo "milestone:   ${{ steps.get_overview.outputs.milestone }}"
          echo "assignees:   ${{ steps.get_overview.outputs.assignees }}"
          echo "reviewers:   ${{ steps.get_overview.outputs.reviewers }}"
          echo "pull_number: ${{ steps.get_overview.outputs.pull_number }}"

      - name: Create pull
        if: ${{ steps.get_overview.outputs.pull_number == '' }}
        run: |
          gh pr create --base ${{ env.MAIN_BRANCH_NAME }} \
            --head ${{ github.event.pull_request.base.ref }} \
            --label '${{ steps.get_overview.outputs.labels }}' \
            --project '${{ env.PROJECT_NAME }}' \
            --reviewer ${{ steps.get_overview.outputs.reviewers }} \
            --assignee ${{ steps.get_overview.outputs.assignees }} \
            --body '${{ steps.get_overview.outputs.body }}' \
            --title 'Release ${{ env.MAIN_BRANCH_NAME }} 🚀'
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Update pull
        if: ${{ steps.get_overview.outputs.pull_number != '' }}
        run: |
          gh pr edit ${{ steps.get_overview.outputs.pull_number }} \
            --body '${{ steps.get_overview.outputs.body }}' \
            --title 'Release ${{ env.MAIN_BRANCH_NAME }} 🚀' \
            --add-label '${{ steps.get_overview.outputs.labels }}'
        env:
          GITHUB_TOKEN: ${{ github.token }}
